# docker run -it --rm --network stack1_my-net --entrypoint /bin/sh curlimages/curl

services:

  lazy-tcp-proxy:
    container_name: example-lazy-tcp-proxy
    image: mountainpass/lazy-tcp-proxy
    environment:
      - DOCKER_SOCK=/var/run/docker.sock
      - POLL_INTERVAL_SECS=10
      - IDLE_TIMEOUT_SECS=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "5432:5432"
      - "27017:27017"
      - "9000-9099:9000-9099"
      - "9003:9003/udp"
    restart: always

  # Note: uses a HTTP keep alive (server side)
  whoami:
    image: traefik/whoami
    container_name: example-whoami
    command: ["--verbose"]
    networks:
      - example-private-network
    labels:
      - "lazy-tcp-proxy.enabled=true"
      - "lazy-tcp-proxy.ports=9001:80"

  # ssh admin@localhost -p 9002
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: example-openssh-server
    networks:
      - example-private-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD_ACCESS=true
      - USER_NAME=admin
      - USER_PASSWORD=password
    labels:
      - "lazy-tcp-proxy.enabled=true"
      - "lazy-tcp-proxy.ports=9002:2222"

  postgres:
    image: postgres:17.6-alpine3.22
    container_name: example-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin}"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "lazy-tcp-proxy.enabled=true"
      - "lazy-tcp-proxy.ports=5432:5432"

  # mongodb://admin:password@localhost:27017/mydatabase?authSource=admin
  mongo:
    image: mongo:7.0.5
    container_name: example-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-mydatabase}
    volumes:
      - mongo_data:/data/db
    labels:
      - "lazy-tcp-proxy.enabled=true"
      - "lazy-tcp-proxy.ports=27017:27017"

  # echo "hello" | nc -u localhost 9003
  udp-echo:
    image: alpine
    container_name: example-udp-echo
    networks:
      - example-private-network
    command: ["sh", "-c", "apk add --no-cache socat && socat -v UDP4-RECVFROM:9003,fork EXEC:'cat'"]
    labels:
      - "lazy-tcp-proxy.enabled=true"
      - "lazy-tcp-proxy.udp-ports=9003:9003"

volumes:
  postgres_data:
  mongo_data:

networks:
  example-private-network:
    driver: bridge
    internal: true
