version: "3.8"
services:
  lazy-tcp-proxy:
    build: ./lazy-tcp-proxy/
    image: lazy-tcp-proxy:latest
    environment:
      - DOCKER_SOCK=/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000-9099:9000-9099"
    restart: unless-stopped
    